project:
  created_date: '2025-10-29T01:48:46.451851+00:00'
  description: 专业的科研文献/报告审核Agent，能根据用户提供完整文献，结合在线检索PMC文献的工具，进行犀利的评价与反馈
  name: pubmed_literature_review_agent
  updated_date: '2025-10-29T02:00:14.402729+00:00'
  version: 1.0.0
